server:
  port: 8088

spring:
  application:
    name: auth-service
  datasource:
    url: ${AUTH_DB_URL:jdbc:postgresql://localhost:5439/auth_service}
    username: ${POSTGRES_USER:airport_user}
    password: ${POSTGRES_PASSWORD:airport_pass}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  jwt:
    secret: ${JWT_SECRET:dev-auth-secret-change-me-32-bytes-min}
    expiration-hours: 24
