server:
  port: 8087

spring:
  application:
    name: security-clearance-service
  datasource:
    url: ${SECURITY_DB_URL:jdbc:postgresql://localhost:5438/security_clearance}
    username: ${POSTGRES_USER:airport_user}
    password: ${POSTGRES_PASSWORD:airport_pass}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: security-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.add.type.headers: false
      spring.json.trusted.packages: "*"

app:
  topics:
    security-events: security-events

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info